language: python
python: 3.7
env:
  matrix:
   - TOXENV=py34
   - TOXENV=py35
   - TOXENV=py36
   - TOXENV=py37
   - TOXENV=flake8
install:
  - pip install tox
  - if test "$TOXENV" = py37 ; then pip install coveralls ; fi
script: tox
after_script:
  - if test "$TOXENV" = py37 ; then coveralls ; fi
